# Initial state of the FSM

initial_state: "NORMAL_JOYSTICK_CONTROL"


events: # Maps from subscribing topic to signal ids
  joystick_override_on:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  joystick_override_off:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False
  charging_station:
    topic: "lane_controller_node/bat_soc"
    msg_type: "BoolStamped"
    trigger: True

# Define nodes
nodes:
  anti_instagram: "anti_instagram_node/switch"
  line_detector_node: "line_detector_node/switch"
  lane_filter_node: "lane_filter_node/switch"
  ground_projection_node: "ground_projection_node/switch"
  # extras added
  apriltag_node: "apriltag_detector_node/switch"

# Define state transitions

global_transitions:
  joystick_override_on: "NORMAL_JOYSTICK_CONTROL"
  joystick_override_off: "LANE_FOLLOWING"

states:
  NORMAL_JOYSTICK_CONTROL:
    active_nodes:
      - anti_instagram
      - lane_filter_node
      - line_detector_node
      - ground_projection_node
      - apriltag_node
    lights: "GREEN"
  LANE_FOLLOWING:
    transitions:
      charging_station: "LANE_FOLLOWING_AVOID"
    active_nodes:
      - anti_instagram
      - line_detector_node
      - lane_filter_node
      - ground_projection_node
      - apriltag_node
    lights: "RED"
  LANE_FOLLOWING_AVOID: #Variable für Charge Control
    active_nodes:
      - anti_instagram
      - line_detector_node
      - lane_filter_node
      - ground_projection_node
      - apriltag_node
    lights: "BLUE"